### ISSUE TITLE
Color mappings fail for csv in UTF8-encoding and color mapping in first column

### ISSUE THREAD

**Issue by tofalemo** [berteh/ScribusGenerator#113]
Scribus version: 1.5.4
CSV encoding: UTF8
Area: Color mapping

Color mappings fail when csv is saved as UTF8 and color mapping is in first column.

This seems to be because the first column gets prefixed by "\xef\xbb\xbf"

**Example**
VARNAMES [['\xef\xbb\xbfdummy', 'bgcolor', 'name', 'text', 'points', 'level', 'symbolimage']

**Workaround** 
Add dummy column first in csv. 

Attached example with dummy column.
[Cards.zip](https://github.com/berteh/ScribusGenerator/files/2484986/Cards.zip)

**Comment by berteh** [comment]
Hello @tofalemo 

EF BB BF in hexadecimal is the UTF-8 BOM: http://www.unicode.org/faq/utf_bom.html#BOM
I guess your CSV editor did not ask you if yon wanted to save as CSV with BOM or without BOM.

I'll test if using [python-unicodecsv](https://github.com/jdunck/python-unicodecsv) instead of the python [native csv library](https://docs.python.org/2/library/csv.html) solves this issue and works in all cases.

**Comment by berteh** [comment]
or yet better (as a note to self to test), per https://tobywf.com/2017/08/unicode-csv-excel/

    with open('test.csv', 'w', encoding='utf-8-sig', newline='') as fp:

**Comment by berteh** [comment]
seems to be fixed by updating to latest (python3) script and scribus. kindly test and get back in touch if you still experience the problem.
