### ISSUE TITLE
give feedback on generation end

### ISSUE THREAD

**Issue by berteh** [berteh/ScribusGenerator#12]
tell the user if the generation was successful (or not) in the GUI and CLI.
maybe close script GUI on successful generation.

**Comment by MartinZaske** [comment]
Thank you berteh, this will be a super-useful enhancement!

Since my runs are taking several minutes and the screen goes very funny (focus is jumping between Scribus and other windows), I would much appreciate a confirmation.

If you want to consider user-input, I would rather have the confirmation in the GUI and then close it myself. (Often I need to run several mail-merges anyway, because I am using modified Scribus documents for my different languages).

**Comment by berteh** [comment]
thank @MartinZaske for this useful input. 
Will rather consider not shutting script GUI down on successful run then.  If you can feel free to contribute a code change to this project, I'd gladly test & integrate it!

**Comment by berteh** [comment]
By the way, @MartinZaske, if you often run multiple mail-merges you should have a look at the [command-line interface](https://github.com/berteh/ScribusGenerator#running-scribus-generator-from-the-command-line). It has been designed to make these things much faster (but only generates SLA, no pdf).

You can for instance run ScribusGeneratorCLI.py on many different slas using always the same data set (-c option), or in a way each sla uses it's own data set (simply name the csv with the same name as the sla, locate it in the same directory, and do not use the -n option).

Many other uses are possible (check out the new "--single" option too!), and kindly add your examples and favorite results to the [wiki](https://github.com/berteh/ScribusGenerator/wiki)!
