### ISSUE TITLE
why do you have a composer.json file?

### ISSUE THREAD

**Issue by aoloe** [berteh/ScribusGenerator#136]
... as far as i know `composer.json` are only useful for php projects...

**Comment by berteh** [comment]
Indeed.

It has been aded by users who use SG in their PHP workflow per #132.

I would rather have seen such a metadata info file elsewhere as the project
root, but that must be its place by convention.

Other option would be to create another SGphp module, with the composer
file + SG code... but I first wanted to check if it bothered others...
since I personally didn't care much.

Any thoughts on this? @S1SYPHOS @daybugging ?

Thanks for the interest.

**Comment by aoloe** [comment]
ok, i could not find many details in the ticket about how they use scribus in their php workflow...

i have the feeling that i would have done it the some sort of the "the other way" round, but if there is indeed a use for that, well, leave the file in here...

this having been said, it would be nice if @S1SYPHOS or @daybugging could tell more about their workflow... it's always interesting to hear how people use scribus : - ) (if you want to do so, you're welcome to open a ticket in https://github.com/impagina/htdocs-grav-pages/issues and we can try to get a description to put in the showcase section)

**Comment by daybugging** [comment]
By the way, when visiting http://impagina.org/showcase, I'm presented with an `Invalid argument supplied for foreach()` error 😞 

This being said, @S1SYPHOS is currently working on automatizing some kind of recommended book list, published by a local child & youth book store, powered by [this library](https://github.com/Fundevogel/pcbis2pdf) using ScribusGenerator.

If there was an easy way to add git submodules to composer packages, we could publish `sg-php` (or whatever), with `composer.json` and ScribusGenerator as git submodule ..

**Comment by aoloe** [comment]
@daybugging oops, the 404 does not seem to be working...
i've now added a first showcase and you should now be able to follow the link (and i will fix the 404 later...)

looks likes an amazing project and i would be delighted to feature in this still so empty showcase section as soon as you have a pdf to show : - )

**Comment by S1SYPHOS** [comment]
Hello there, @aoloe!
As mentioned before, I'm part-time developing a small library around the german wholesale book distributor KNV and its ERP system, 'pcbis.de' for a (very little, but lovely) bookstore (like @debugging said, only children & youth literature/books), called [Fundevogel](https://fundevogel.de/en).

Two times a year they go through novelties and special books they like and collect them in a huge list on 'pcbis.de', normally opening a word document & copying everything (!!) by hand, including various information, texts, pictures, .. when I heard they spent days on this, I had to step in. After discovering that said lists could be exported to `.csv`, and being a man of (a limited amount of) PHP knowledge, the path was clear: building what would eventually become [`pcbis2pdf`](https://github.com/Fundevogel/pcbis2pdf).

The power of free & open source was strong in this one, but one quest lies ahead still: DTP software - and I instantly knew I wanted to give Scribus a shot .. so I needed something to get my heavy CSV files in there: ScribusGenerator - and because I wanted a way to "always take a copy with me", I asked if a `composer.json` could be created, and @berteh kindly accepted.

That's [it, basically](https://github.com/Fundevogel/recommended-novelties), yeah - if I ever get my head around a beautiful design & automatize the thing as far as I can, then I'll let you know for sure!
