### ISSUE TITLE
Suggestion: filter potions

### ISSUE THREAD

**Issue by EngDarkRoseAlchemist** [berteh/ScribusGenerator#143]
Please, include filter, a selection according to many fields of CSV file and, SQLite and PostgreSQL databases.

**Comment by berteh** [comment]
Hello.

I did not want to get into that level of data manipulation with this tool,
since existing database engines are meant to do this and powerful at it too.

I'd recommend storing the filters and queries you are interested in in your
database, and then simply make a 2 line script that 1) runs them to export
to the right CSV file and 2) runs ScribusGenerator from the command line on
this CSV.

examples for different databases are in the SG wiki:
https://github.com/berteh/ScribusGenerator/wiki/Other-data-sources#export-from-a-standard-database

Please add more examples, eg from Java databases or other ETL engines.


That being said you can still use the 'range' parameters (''from'' and
''to'') to use just a subset of your data, using sorting mechanisms in your
queries. But I find it cleaner to work with different CSV files altogether.

If you find a filter is really important feel free to propose code. I'd
gladly review and integrate something that filters data on empty/not
empty/some text comparison or arithmetic comparison.... but again: looks to
me like this is reinventing a wheel, even if it can be convenient.

Have a nice day.
Berteh.

**Comment by berteh** [comment]
I close the issue as the workaround seem satisfactory to me. feel free to re-open if you think it's important or you want to implement this yourself. thanks.
