### ISSUE TITLE
Images in template not showing

### ISSUE THREAD

**Issue by robertharle** [berteh/ScribusGenerator#144]
Hi.  Great tool - thanks for developing.  i have a template scribus file that contains some jpeg images along with text, boxes, etc.  However, when i run the generator script, all the text vars get replaced, various colours change as intended but the images simply disappear. if i do a manual export of the template it looks fine (although obviously no merging, but the images are there).

If anyone has any quick thoughts on what to try, that would be much appreciated - i need to send the merged output to the printers tomorrow and i'm stuck.

FWIW Scribus version is 1.4.7.

Thanks!

**Comment by berteh** [comment]
Hello.
Glad you like the tool, thanks for the feedback.

Are the disappearing images static to your file or are their path
dynamically generated by ScribusGenerator (i.e. they include some %VAR_%)?

In any case missing images is often due to relative path not being
accessible from one file wrt to the original template location.

Are the generated (SLA) files generated in the same directory as the
template? If not please try to move one there and reopen it, to see if that
is the issue.

Have a nice day, and don't hesitate to share your results with
ScribusGenerator in our gallery/wiki!


Le mer. 4 sept. 2019 à 18:56, robertharle <notifications@github.com> a
écrit :

**Comment by robertharle** [comment]
Ah, it was indeed the file not being in the same directory - that's 
fixed it!

Thanks so much.

**Comment by berteh** [comment]
You're welcome.
