### ISSUE TITLE
Please help! I'm a farmer and I have zero coding experience

### ISSUE THREAD

**Issue by cloudcapmushroomco** [berteh/ScribusGenerator#153]
Please help! My wife and I run a small mushroom farm, and started using scribus generator to automatically create labels for bags of mushrooms for our customers.  Which was amazing; it saved so much time! It was working fine until today. Now when I run the script it has errors, does an incomplete export, and outputs a bunch of .sla files instead of .pdf's. I have no idea how to decipher any of this error message. I haven't even been able to find the log. I have a workaround for orders for today, but if anyone can help it would be greatly appreciated. THANKS IN ADVANCE!!!

![2020-05-11](https://user-images.githubusercontent.com/65204704/81629080-25298e00-93b7-11ea-8ae3-657a006f26c3.png)

**Comment by berteh** [comment]
Hello Chris.
Let's find a solution quickly!

What changed in your setup between this time and the last time when ScribusGenerator did work well?

Did you modify your label template a little bit? Or  the way your CSV is created?

Do you see SLA files being generated for ALL the labels you expect or is it stopping at some stage? If the last SLA you see is the line 38 of your CSV data, then there's a chance my script (or Scribus) struggles with something in the data of the next line. Maybe some unknown character, or some linebreak. Please try again after removing that data line completely (move the SLAs to another directory first, or you won't be able to tell if there's a difference)... and if that works put this data line back and look at it in details to find the culprit.

The log file should be in c:/user/chris ponti/Scribus Generator.log.  Please copy-paste the last 30-40 lives of that fine here (using notepad), or join it as an attachment.

Cheers.
Berteh.

**Comment by cloudcapmushroomco** [comment]
Thank you!
There was an old school "<3" emoji with one of the names in the CSV and
that was breaking it.
Fixed.
THANK YOU SO MUCH!

**Comment by berteh** [comment]
I'm glad I could help.

Thanks for your bug report, I'll try to improve the code so the feedback on error is more understandable by the user; along with #138 and #120.

have a nice day.

**Comment by cloudcapmushroomco** [comment]
Thank you.
One more thing. When I output a full page sla and choose the merge pdf
option there is a margin between pages that makes the file unusable. I have
been using xodo editor to merge all the separate pdfs after running your
script as a workaround. That would be nice to have working as well. Thanks
again!

**Comment by berteh** [comment]
Strange.... Aye you sure you don't have a margin in your document display properties that would be there but simply not showing since you have a single page?

SG does not add an extra margin, but it does shift the page content 'down' to the next page according to document size, page height and margin defined in the template document.

Could you please try to generate a merged SLA (not pdf) and open it with Scribus, to try to find what is exactly causing this 'margin' shift effect?

If you don't find it and there's nothing sensitive in your template kindly send it to me we some dummy CSV (can be the same line repeating a few times), I'll try to trace and fix the problem.


I had once a similar problem when I designed a template from a US page size example, that I then tried to A4. Scribus did update the page height, but not some other internal value (I don't remember wich), leading to SG shifting the elements further down of 1cm at each page... After 30 pages i couldn't see a thing :-\

**Comment by berteh** [comment]
And please next time open a new issue report when changing the topic. It makes keeping track of work to do easier. Thanks.

**Comment by berteh** [comment]
closing for lack of answer. feel free to open a new issue with more details, attach the template if possible.
