### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by candideu** [berteh/ScribusGenerator#156]
Hello,

I am using Scribus 1.5.5 on a Windows 10 laptop and received this error when I tried the "Next_Record.sla" file that came with the download (it's in the "Example" folder):

> Traceback (most recent call last):
>   File "<string>", line 10, in <module>
>   File "C:\Program Files\Scribus 1.5.5\share\scripts\ScribusGenerator.py", line 401, in <module>
>     main_wrapper(sys.argv)
>   File "C:\Program Files\Scribus 1.5.5\share\scripts\ScribusGenerator.py", line 388, in main_wrapper
>     main(argv)
>   File "C:\Program Files\Scribus 1.5.5\share\scripts\ScribusGenerator.py", line 379, in main
>     root.mainloop()
>   File "C:\Program Files\Scribus 1.5.5\python\lib\lib-tk\Tkinter.py", line 1129, in mainloop
>     self.tk.mainloop(n)
>   File "C:\Program Files\Scribus 1.5.5\python\lib\lib-tk\Tkinter.py", line 1545, in __call__
>     self.widget._report_exception()
>   File "C:\Program Files\Scribus 1.5.5\python\lib\lib-tk\Tkinter.py", line 1297, in _report_exception
>     root.report_callback_exception(exc, val, tb)
>   File "C:\Program Files\Scribus 1.5.5\python\lib\lib-tk\Tkinter.py", line 1900, in report_callback_exception
>     traceback.print_exception(exc, val, tb)
>   File "C:\Program Files\Scribus 1.5.5\python\lib\traceback.py", line 125, in print_exception
>     print_tb(tb, limit, file)
>   File "C:\Program Files\Scribus 1.5.5\python\lib\traceback.py", line 67, in print_tb
>     '  File "%s", line %d, in %s' % (filename, lineno, name))
>   File "C:\Program Files\Scribus 1.5.5\python\lib\traceback.py", line 13, in _print
>     file.write(str+terminator)
> IOError: [Errno 9] Bad file descriptor

**Comment by berteh** [comment]
Hello.

The error text (IOError: [Errno 9] Bad file descriptor) looks to me like the script cannot write something to some file.

The only file it should be trying to write something to at that stage is the log file, which should be C:/users/yourself/.scribusGenerator.log. So I guess the location of this log file is actually wrong or pointing to a directory that is not accessible.

Could you please redownload ScribusGenerator to another directory where you're sure your user has write access? Like in your Documents folder, and run it from there.

If that works it should point that the issue lies in the location of the log file being wrong for Win10.

In that case please edit the file C:\Program Files\Scribus 1.5.5\share\scripts\logging.conf, on line 22 and change '~/.scribusGenerator.log' to 'c:\temp\scribusGenerator.log', and try again running the script like you did on the first time (the one leading to the error).

If that does not solve the issue please copy paste the content of your C:/users/yourself/.scribusGenerator.log file here, it should help finding the issues.

Thanks.

**Comment by berteh** [comment]
any improvement ?

**Comment by candideu** [comment]
Hi Berteh,

Executing the script from my "Downloads folder" worked. When I tried
executing it from the Scribus share\scripts folder, it wouldn't do
anything. I couldn't find the logging.conf file to edit, but I suppose that's
not an issue if the script can be executed (as long as it's from another
location).

Thank you!

**Comment by berteh** [comment]
Thanks for the report.
I tried to explain the location problem better in the documentation; kindly have a look and propose a better wording if you have suggestions.

The Next_Record.sla is meant to use the examples/Business_Card.csv data file... but any other would do too.

**Comment by egdedudette** [comment]
I am having the same problem. here is the error I get. I have the script in my download folder on windows. Can you help?

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "<string>", line 21, in <module>
ModuleNotFoundError: No module named 'Tkinter'

**Comment by candideu** [comment]
@egdedudette Which version of Scribus are you using?
