### ISSUE TITLE
How to automate SVG import with ScribusGenerator?

### ISSUE THREAD

**Issue by zelyev** [berteh/ScribusGenerator#164]
Hello,

first I want to thank all the developers behind ScribusGenerator. In the last weeks I was able to create beautiful documents with the data coming from a single CSV file.

Now I would like to ask how ScribusGenerator could automate the SVG-file import. I tried it the same way as with other images, but it does not seem to work. I created an image frame and selected a dummy %VAR_IMG% file. And in the CSV I entered "file.svg", and the file exists in the same folder. The exported test PDF however is just empty.

Any suggestions?

**Comment by berteh** [comment]
Hello @zelyev 
Importing SVG as ima
ge frames does work in ScribusGenerator, just as with png or jpg images; just make sure your (relative or absolute) svg file path matches the generator *output* directory.

Unfortunately Scribus sometimes renders the included svg in really low resolution, so you should check out the dpi (and or size) or your source material.

There is unfortunately no way to include dynamically vector files (pdf or svg) with ScribusGenerator, because of the way Scribus imports them (from the menu File > Import > Vector) by converting them one-the-fly to scribus objects. Which is great for direct editing in Scribus, but not for including external files by reference.

**Comment by zelyev** [comment]
Hello @berteh,

**Comment by berteh** [comment]
I don't know. But you could ask your question to the Scribus team, either via their forum or mailing list, see scribus.net website.

This script does not provide additional capabilities aside from document generation.

Manually importing a vector file (via file > import > vector) allows you to 'ungroup' the imported shape and then zoom as much as you want... more or less: clipping the zoomed group is not straightforward.

**Comment by zelyev** [comment]
Alright, thank you very much @berteh

**Comment by datavectors** [comment]
Although this issue is now closed it fits the workflow I have in mind [as issue posted here](https://github.com/berteh/ScribusGenerator/issues/167). If there is an impact on SVG esolution then my approach (for automation) will be to jump out of SG for SVG import and apply automation script to the Scribus GUI. Emulating user actions. The automation tool will depend on the OS in use.

**Comment by berteh** [comment]
AFAIK Scribus does not copy-paste the SVG when it imports as vector, but really *converts* most objects to Scribus PageObjects, so a 'simple' SVG injection would not work.

You can always script the high definition rendering of your SVG as PNG images this be then included by SG as images.

If you need to script the export SVG>PNG (or other) you may be interested in another script of mine: https://github.com/berteh/svg-objects-export

Good luck.
