### ISSUE TITLE
Script Error when Save Settings is enabled.

### ISSUE THREAD

**Issue by MparkG** [berteh/ScribusGenerator#170]
![image](https://user-images.githubusercontent.com/26872340/106927003-fd7f1080-6711-11eb-82b3-fde39c36adb9.png)

**Comment by berteh** [comment]
Thanks for the report. 

This error might be because recent python 3.9 deprecated that particular ``getChildren`` method, which would be fixed by updating your scribus generator with latest release from branch python3: https://github.com/berteh/ScribusGenerator/archive/python3.zip

kindly let me know if that fixes it.

**Comment by MparkG** [comment]
it fixes the error, but does not store anything. idk where it would store settings. i place the script files in the /usr/share/.. folder for the installation. maybe there are issues with file permission.
I use the script by script though, so i dont really bother with the option anymore.

**Comment by berteh** [comment]
The option are saved in your SLA template, for future use.

This error seems relating to python 3.9 having deprecated some old methods, incl. Getchildren.

Could you please update your script with the last (python3) version and try again? This should have been fixed by the last update a few days ago.

**Comment by berteh** [comment]
I'll check again when exactly the options are saved. The used to be a race condition problem with Scribus overwriting the template on your next save without reloading the file with the saved options first...  They are actually saved in a XML attribute on the Scribus 'document' element, as to be project specific.

**Comment by berteh** [comment]
should now be fixed, please update. 
Saving works again from the GUI and the CLI in python3 version; Thanks for the issue report.
