### ISSUE TITLE
%SG_NEXT-RECORD% bug when #of CSV entry != amount template consumes in one page.

### ISSUE THREAD

**Issue by BrunoDSL** [berteh/ScribusGenerator#173]
I'm having a pretty hard time understanding how to use the feature. The provided examples work, but I always get this error when I try to do it myself:
![image](https://user-images.githubusercontent.com/9355061/109711269-70e33900-7b7d-11eb-935b-554f99ce073f.png)

Before pointing out that the variable is at the wrong place, I was trying that because other post tells to do that. There's no consistensy. Documentation says one thing, but the example where that feature is demonstrated does the opposite and works. It's hard to know if it's an error on my part, Windows or something else. Python tracebacks are useless if you don't know how the script is implemented or is supposed to work.

And to add more insult to the injury, the only video that teaches you how to use script is from a version of the script that doesn't even have the feature.

**Comment by berteh** [comment]
Hi @BrunoDSL 

Sorry to read the multiple records feature brings you so much trouble. I didn't take the time to make a more up-to-date video to illustrate it.

Most of the issues (many) users encountered with %SG_NEXT-RECORD% are usually due to the script behavior. Scribus Generator reads your SLA (template) file in a sequential order, and loads the next record data instantly as soon as it reads the this token. 

Problem is that Scribus does not always store objects in the SLA file in the order they appear in your page, but rather in the order you create them.

So one possible workflow to get your design right can be to first create a text box with the next record token. It can be left outside of the print/page range or simply turned "non printable" from the object properties. Then create all items you wanna see duplicated. Group it all together and duplicate/layout to you hearts content... then delete the very first next record token (or it will result in skipping the first row of data). All explained here: https://github.com/berteh/ScribusGenerator/issues/157#issuecomment-646950248

Another user managed to use the "group/ungroup" to fix the order of items and next record token:
https://github.com/berteh/ScribusGenerator/wiki#cards-deck-walkthrough


The only way to be 100% sure is to check (and opt. manually move) the next record token in the SLA code to the place closest to the block you wanna duplicate, preferably after the last variable use. Then duplicate content + token block, layout, and remove first (resp. last) superfluous token.

Hope this thelps. don't hestitate to attach your sla and sample csv for me to have a look in case of need.
Berteh.

**Comment by BrunoDSL** [comment]
I get the same error. There's also one extra thing that happens. This error only appears with the single merge option enabled. If I don't have that selected, the script succeeds, but no files of any type are created.

**Comment by berteh** [comment]
Which version of ScribusGenerator are you using ? I see you run Scribus 1.5.6.1 that ships Python3, so please make sure to use the python3 version of the generator script: https://github.com/berteh/ScribusGenerator/archive/python3.zip

Could you please attach your ScribusGenerator.log file here ? and even your SLA + csv (opt. anonymized) if possible, so I can try to reproduce this problem ? (you'd need to add ``.txt`` at the end of the file name though, as sla and csv extensions are not accepted as attachments.

**Comment by BrunoDSL** [comment]
[scribusGenerator.log](https://github.com/berteh/ScribusGenerator/files/6072964/scribusGenerator.log)

[Uploading Tags_
[Tags_Template.sla.txt](https://github.com/berteh/ScribusGenerator/files/6072968/Tags_Template.sla.txt)
Template.csv.txt…]()

**Comment by berteh** [comment]
Indeed I can reproduce your issue, thanks for the files.

Problem happened when the csv contained less entries (11 for you) than the template consumes in one go (24 in your example).

Moreover having more entries (tested with 30) does not properly shift the duplicated content to the next page anylonger, nor does it duplicate just the local template section but the whole first substituted page instead... so I'll need a bit more time to sort this out.

**Comment by berteh** [comment]
should now be fixed. Kindly update to the last python3 script version; and test again.
thanks for the issue report.

**Comment by berteh** [comment]
and about the difficulty to use %SG_NEXT-RECORD% here is maybe my most detailed info so far:
https://github.com/berteh/ScribusGenerator/issues/157#issuecomment-647188950
