### ISSUE TITLE
Generate custom colors based on RGB codes?

### ISSUE THREAD

**Issue by dankeller** [berteh/ScribusGenerator#177]
Is it possible to create a color variable that references a column in the CSV containing RGB codes (e.g. #B4FF00) to use the color specified in the CSV?

**Comment by berteh** [comment]
not directly no, because of way Scribus handles colors: you need to create a color swatch and import it in scribus... then use these colors names into your CSV variable.

Of course there is nothing to prevent you from creating a swatch of colors which names are their RGB code. I thinkg you can import Gimp color palettes as well (maybe the easiest to create a list of your colors with a script or spreadsheet), and the colors of an imported SVG objects too, if I remember correctly.

Some swatches already included in Scribus are: https://github.com/scribusproject/scribus/tree/4ccc75ee9899f5a4c27178b43340a8428029fbe4/resources/swatches
