### ISSUE TITLE
ScribusGenerator for Python3 with Scribus 1.5.7 - Multiple records in merge mode

### ISSUE THREAD

**Issue by TomGruenewald** [berteh/ScribusGenerator#192]
Hello,

I am new to Scribus. I have downloaded Scribus 1.5.7 (the current development version) and the recent "ScribusGenerator for Python3".
I try the use the feature "Multiple records in merge mode" using the tag %SG_NEXT-RECORD%. But my simple example fails. Can you please tell me what I am doing wrong here.

[test.zip](https://github.com/berteh/ScribusGenerator/files/7877681/test.zip)

Thank you for your support,
Tom

**Comment by TomGruenewald** [comment]
I have upgraded to Scribus 1.5.8 . The feature "Multiple records in merge mode" using the tag %SG_NEXT-RECORD% is still not working.
Therefore I have installed Scribus 1.4.8 with the current "ScribusGenerator master edition". With this combination is the feature working.

**Comment by berteh** [comment]
sorry Tom for this late feedback.

I just ran your "test" example with Scribus 1.5.6.1 (which is the most recent version easily available for my older Ubuntu distribution) with no problem at all (in merge mode for both SLA and PDF generation) after the last (December) update from the Scribus Generator script (version python 3).
so please try downloading the script again as a few bugs have been fixed.

I would recommend removing the %SG_NEXT-RECORD% at the bottom of the last box though, as SG automatically detects the end of your template and loads next record when starting the new page... otherwise you will "skip" one record every time.

Hope this helps.

**Comment by TomGruenewald** [comment]
I am using Scribus 1.5.8 right now. I did most of the work by copy and paste.
I close this issue, because it is already old. Thank you for your support.
