### ISSUE TITLE
No module named 'Tkinter'  -- solved

### ISSUE THREAD

**Issue by MaartenFokkinga** [berteh/ScribusGenerator#206]
In Ubuntu 22.04 (just installed on a new, refurbished machine) everything seems to run fine except ScribusGenerator; it produces the following message:

`Traceback (most recent call last):`
  `File "<string>", line 11, in <module>`
  `File "<string>", line 21, in <module>`
`ModuleNotFoundError: No module named 'Tkinter'`

I use Scribus version 1.5.8 and just downloaded the latest version of ScribusGenerator.

How to solve? What should I do?

**Comment by MaartenFokkinga** [comment]
I've changed `Tkinter` into `tkinter` everwhere in ScribusGenerator.py and now I get the message: `ModuleNotFoundError: No module named 'tkMessageBox'`

**Comment by MaartenFokkinga** [comment]
The issue is solved by the following steps (of which the first one might be superfluous):

- `sudo ln -s /usr/bin/python3 /usr/bin/python`
- download and use `ScribusGenerator-python3.zip` instead of `ScribusGenerator-master.zip`

**Comment by berteh** [comment]
As you found out yourself (but for future refence): this problem is due to the fact Scribus 1.5.6 (and later) ship with Python3, therefor you need to download the ScribusGenerator branch for Python3.

More details in the documentation at: https://github.com/berteh/ScribusGenerator#how-to-install-scribus-generator-

As soon as the stable branch of Scribus gets upgraded to Python3 you shouldn't suffer for this problem anymore.

**Comment by MaartenFokkinga** [comment]
Thanks!!

Maarten


Op di 20 dec. 2022 om 15:25 schreef Berteh ***@***.***>:
