### ISSUE TITLE
csv import keep text with text styles, bold, list, em, ...

### ISSUE THREAD

**Issue by leboiss** [berteh/ScribusGenerator#208]
Hello all. 
I am using scribusGenerator to import data from a csv file.
Is there a way to retain or add style to the text? 
I want to keep the text style like bold, list, underlined text...
Maybe by using a script, using markdown or something?

Thanks for your work

**Comment by berteh** [comment]
Hello.
AFAIK there's no easy way to add style in the imported text, since scribus uses it's own syntax for styled elements.

For lists I used to "simply" use manual linebreak and then nice-looking UTF symbols for bullets, such as any of https://www.utf8icons.com/subsets/miscellaneous-symbols-and-pictographs

There were attempts at a module that does import markdown, but I have no clue if/how it works: https://github.com/aoloe/scribus-plugin-gettext-markdown

**Comment by berteh** [comment]
if you found any solution that might integrate nicely with ScribusGenerator kindly lets us know !
