### ISSUE TITLE
Cannot Fetch image from folder

### ISSUE THREAD

**Issue by emtmedia** [berteh/ScribusGenerator#210]
I have apparently done as described on ScribusGenerator presentation page (https://github.com/berteh/ScribusGenerator) but I can't get the image to be fetched to my canvas (all the other data is fetched ok). I'm using Scribus 1.5.8 on Windows 10 and have Python 3 installed, I have assigned a variable to the image frame successfully as taught, then tried renaming one duplicated file in my image folder to "%VAR_pic% (tried with and without the file extention [png]), the image field header in my CSV file is "**pic**", therefore, the variable for the image frame is %VAR_pic%, also, the file name below that field header is the name of the person like "John Doe.png", and this file "John Doe.png" exists in the image folder.  Moreover, I don't understand what the statement "**Just make sure to handle the file extension either in the file name, or in the CSV data, but not in both.**" under the topic _Dynamic Images_ on the explanation web page mean. Another issue is that while I go to Get Image to open the file picker to type %VAR_pic% in the filename field in the file picker, the OK button is greyed out, thus I can't validate the operation until I click on any file in the file picker, then the OK button comes alive again, but now the file I clicked becomes the picked one, even if I rename it to %VAR_pic% it will take the file I picked anyway. What could be wrong with my take on this??

**Comment by berteh** [comment]
since you closed the issue I guess you found a solution.

as explained in the document, the trick is to duplicate one of your pictures and rename it with the variable name you want to use in scribus, in your case that file would be called "%VAR_pic%"   *without any extension* since the extension is included in your CSV data.

then just pick that file from the image file select dialog in scribus.

**Comment by berteh** [comment]
the comment you pinpoint in bold is to note that you should not call this  "placeholder" duplicate image "%VAR_pic%".png (with an extension), as otherwise the subsitution would lead to try to load the file John Doe.png.png  (first extension from your CSV data, second from the original file path)... that does not exist.
