### ISSUE TITLE
support linked frames in merged mode

### ISSUE THREAD

**Issue by berteh** [berteh/ScribusGenerator#22]
reported by @garydale

I am flowing text through several text frames. When I create individual Scribus files, it works. However when I create a single output file, the subsequent page contain a group of frames with no text flow - I only see the first text frame's text.

In merged output mode, generated text frames become unlinked.

**Comment by garydale** [comment]
On 13/09/15 05:41 PM, Berteh wrote:
>
> reported by @garydale <https://github.com/garydale>
>
> I am flowing text through several text frames. When I create 
> individual Scribus files, it works. However when I create a single 
> output file, the subsequent page contain a group of frames with no 
> text flow - I only see the first text frame's text.
>
> In merged output mode, generated text frames become unlinked.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/berteh/ScribusGenerator/issues/22>.
>

Doing a quick look at the various .sla files and have come up with the 
following:
- the page a PAGEOBJECT is on is the property "OwnPage". This is 
generated correctly.
- PAGEOBJECTs don't seem to have an explicit number. Instead their 
number seems to be their order among PAGEOBJECTS with the same OwnPage.
- PAGEOBJECT numbers start at 1. The first object seems to have that number.
- NEXTITEM refers to the next linked object in the chain.
- BACKITEM refers to the previous linked object in the chain.
- a reference of -1 indicates no next or previous object.

The problem seems to be the NEXTITEM and BACKITEM links are always set 
to -1 after the first page.

I think I may be able to fix this problem with sed if you can't correct 
it quickly. I'm already later than I wanted to be to get this out.

**Comment by berteh** [comment]
@garydale should work now. I tested linked frames in merged output mode with Scribus 1.4.3 and 1.5.1svn, both worked.  kindly test and let me know.

**Comment by garydale** [comment]
1) looks good. Every page seems to have the correct information.
2) something weird happened while I was using the previous version. In order to try the NEXTITEM and BACKITEM substitutions I thought would correct the problem, I gave each of the text frames a meaningful name then tried to run a regex replacement.

While investigating why it failed, I noticed that the NEXTITEM and BACKITEM links actually already had the correct values - even though the links weren't working. Apparently my musings in the previous post were wrong.

Thanks!
