### ISSUE TITLE
How to set my layout as portrait or landscape dynamically

### ISSUE THREAD

**Issue by ignutanz** [berteh/ScribusGenerator#221]
My csv will specify in each row whether the layout has to be portrait or landscape. How can i make each generated sla be in the layout specified in each row. eg; If the layout is specified as landscape in the row, the corresponding generated sla should be in landscape layout

**Comment by ignutanz** [comment]
I created one landscape file and a copy of it changing orientation to portrait. I find the following changes using diffchecker showing changes in portrait as compared to the landscape file:

- PAGEWIDTH,PAGEHEIGHT properties are exchanged inside <DOCUMENT
- ORIENTATION="1" changed to ORIENTATION="0" inside <DOCUMENT
- Size="" changed to Size="Custom" Inside the <PAGE
- All ItemID properties inside each <PAGEOBJECT changed to new value 

How should i create the SGAttributes

**Comment by ignutanz** [comment]
I added an SGAttribute named ORIENTATION with value %VAR_orientation% and provided a column inside the csv input with values as 0 and 1 on alternative rows. But I find that all the generated sla files are still in the landscape orientation.

**Comment by ignutanz** [comment]
i find that the orientation and pagewidth,pageheight changes in the attributes of the resulting file while passing it through the csv input file, but visually there is no difference!!

**Comment by DavidPesticcio** [comment]
Just a thought - but I suspect the values that changed are needed together to inform other things - the dimensions of a page are essentially irrelevant without an orientation, certainly to a printer etc.

I.e. the shape is not an indication of it's orientation, except by convention or prior knowledge.

A bit like the marker on a map to inform you of which direction is North, the map itself tells you nothing unless you know already this - hence the symbol for North. :smiley:

**Comment by berteh** [comment]
Hello.
I tried really hard to implement this, but to no avail. Sorry.

I did find a way to tailor objects width and position per the size of their parent page, but you still need to click on each page and change it's orientation manually. It goes fast but is still manual.

If interested attached is a sample template and Spreadsheet used to compute the relate page dimension, positions and objects locations. test is using the dimensions of "Letter" format, but easily adapted to others.

[orientation-calculator.ods](https://github.com/user-attachments/files/15749869/orientation-calculator.ods)
[orientation-test.sla.txt](https://github.com/user-attachments/files/15749870/orientation-test.sla.txt)
[orientation-test.csv](https://github.com/user-attachments/files/15749871/orientation-test.csv)

objects are already in place or stretched per page orientation, but page "background" still needs to be manually rotated before getting the expected result:
![image](https://github.com/berteh/ScribusGenerator/assets/36950/d49600c4-73b8-4387-aeb1-10c985cb8333)


If you're interested in the technical specifics of the obstactle (and for my own note): I find no way to store the (new/oriented) page size information on the Scribus (XML) <PAGE> element... as this one does not support the "Attribute" mechanism available only on <PAGEOBJECT>.  And since Scribus does not store the <PAGEOBJECT> as a child of its parent <PAGE> but at a random place in the SLA files (likely by order of creation?) I cannot easily find the parent page of an SGAttribute to orient the said page accordingly.  To make things even worse the XPath engine of eTree does not support advanced queries, making other type of relations (eg current-position()-1) unusable, that would have been a possible workaround for "simple" templates containing a single page to be oriented/resized: https://docs.python.org/3/library/xml.etree.elementtree.html#supported-xpath-syntax
