### ISSUE TITLE
Missing some texts from csv

### ISSUE THREAD

**Issue by Juan-UAH** [berteh/ScribusGenerator#231]
Some texts from the CSV file are displayed while others don't.
It does not matter if I change them from a row to another. I.E, The texts visibles are always visible, and don't be affected by the row in wich they are. Same with the non visible texts, never visibles. Same text in different boxes is seen and unseen.
Not errors on the screen nor in the log, and PDF created.

Tried plain text, changing order in CSV, changing the sla file... nothing works.

I am attaching the sla, csv and PDF files.

[frenchInfo.zip](https://github.com/user-attachments/files/16056525/frenchInfo.zip)

**Comment by berteh** [comment]
Hello. Sorry for late reply. 

I juste tested your template with a another (simplified) data set (attached) and the result seems perfect, aside from a forgotten "Serie"  box in the 4th element. So I guess the problem lies in the data file, will have a more thorough look.

[frenchInfo_debuggingOrder.csv](https://github.com/user-attachments/files/16551897/frenchInfo_debuggingOrder.csv)

**Comment by berteh** [comment]
got it: your "series" text box is too small for the text to be displayed by Scribus. It's not missing, just hidden because it overflows its containing box... just increase the height of the series box and it'll show (delete/move the polygon in front to be able to access it), just as attached.

good luck !

[frenchInfo__single.sla.txt](https://github.com/user-attachments/files/16551970/frenchInfo__single.sla.txt)
(rename .txt in to .sla after download, .sla is not allowed in github)
