### ISSUE TITLE
Error Launching Script

### ISSUE THREAD

**Issue by frankieit** [berteh/ScribusGenerator#34]
Hi, 
on Windows 10 with scribus-1.4.5-windows-x64 (tried also with 1.5.0) and ScribusGenerator-master  trying to launch the script, I get the following:
 
<code>
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "E:\users\myusername\Documenti\scribus\ScribusGenerator-master\ScribusGenerator.py", line 341, in <module>
    main_wrapper(sys.argv)
  File "E:\users\myusername\Documenti\scribus\ScribusGenerator-master\ScribusGenerator.py", line 329, in main_wrapper
    main(argv)
  File "E:\users\myusername\Documenti\scribus\ScribusGenerator-master\ScribusGenerator.py", line 318, in main
    dlg = GeneratorDialog(root, ctrl)
  File "E:\users\myusername\Documenti\scribus\ScribusGenerator-master\ScribusGenerator.py", line 197, in __init__
    self.__ico=PhotoImage(file=self.__pluginDir+'/pic/ScribusGenerator_logo.png')
  File "C:\Program Files\Scribus 1.4.5\lib\lib-tk\Tkinter.py", line 3323, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Program Files\Scribus 1.4.5\lib\lib-tk\Tkinter.py", line 3279, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
TclError: couldn't recognize data in image file "E:\users\myusername\Documenti\scribus\ScribusGenerator-master/pic/ScribusGenerator_logo.png"
</code>

My total ignorance does not allow me to understand a bit of the above. 
Thanks in advance,
Frankie

**Comment by berteh** [comment]
Thank you Frankieit for this feedback, and sorry it did not work instantly for you.

It seemed like png images are not supported in Windows, so I changed it with a gif instead (same image, other format). works for me in Win8.

Kindly re-download Scribus Generator and try again. Hope this is useful to you!
Berteh.

**Comment by frankieit** [comment]
Hi Berteh, 
it works like a charm, thank you very much.

F

**Comment by berteh** [comment]
you're welcome.

**Comment by frankieit** [comment]
Hi again,
last thing I want is to abuse of your kindness but, to make it simple, is
it possible to allow multiple fields on one page?

"Price List style" kind of?


​​
Once more, thank you very much

Francesco

2015-12-09 13:05 GMT+01:00 Berteh <notifications@github.com>:

**Comment by berteh** [comment]
Hello @frankieit 
there's no abuse... I'll let you know if it should get there one day ;)
Just please, next time: open a new issue, as it is on another topic than the error in launching the script we solved.

The topic of multiple fields interests me a lot. I call them "repeating fields" by the way, as you can already have multiple (different) fields on a single page... but each with a single value. I see 2 major questions that need to be answered before I can implement this in Scribus Generator (which I would really like, by the way). Can you please tell me your view on these 2 elements?

Let's take a example of a catalog of products:

- A single page in the generated document would gather products of the same family, say p1 = trees, p2 = flowers, p3 = garden furnitures.
- On each page you'd use the following (non-repeating) variables: category-title, category-picture, and then 
- a table of the products of that family, and for each product you'd use in its table-row the following (repeating) variables: product-name, product-price

My two questions/problems are the following (the first is more problematic to me, so we need to solve it first ;) :

1. How to represent the repeating element (the table row, or the list item) in Scribus (GUI editor) in a user-friendly way, but in a way we can identify which element to repeat and how to repeat it (eg: should the line 2 go below, on the right, on the left, above, elsewhere?).  In short: **how would you represent your list in the sla template** that the generator would use?  (feel free to attach an sla example!). This questions has been touched upon (but not answered) in #11 
1. What data format would you use instead of CSV? XML variants have been discussed in #19, but I'd like to keep on supporting something spreadsheet-like, as it makes the whole approach more accessible to less tech-savy users (hopefully). In short: **how would you represent data for this catalog in excel/open-office** ?

Have a nice day!
B.

**Comment by frankieit** [comment]
Sorry to have messed it up.  

Unfortunately, among the language barriers and my total ignorance, I'm afraid I can't be of any help here. My only experience was with commercial software (Indesign), a lot of trials and back in 2010.

Possibly, I could beta test some solutions, if there will be any and, even in that case, do net expect me to be too techie :-) 

Keep up your good job and thank you very much,
Francesco 

![price list style](https://cloud.githubusercontent.com/assets/9548998/12973659/3bb89966-d0ae-11e5-91f7-54c8e0bcd2c5.jpg)

**Comment by berteh** [comment]
Ok Francesco. Thanks for the idea of copying the way indesign does it... at least it gives me a few suggestions. I'll get back in touch with you if this gets implemented.
