### ISSUE TITLE
trouble with quote symbol in csv file

### ISSUE THREAD

**Issue by mikeevans82** [berteh/ScribusGenerator#45]
Generator has been working great for me but I can't figure out how to put a quote symbol (") into the csv file.  When the symbol is present generator stops with a parse error.  The generator log stops at "merging content" for the row with the symbol.  I've tried using python escape sequences like \" and """ but I get the same error.  If I remove the symbol the generator works on this csv.  Am I missing something?

I opened up the csv in gedit and confirmed UTF-8 encoding.  

I tried this on 2 systems, windows 10 and ubuntu 12.04.  Same error.

[scribusGenerator.log.txt](https://github.com/berteh/ScribusGenerator/files/257438/scribusGenerator.log.txt)

**Comment by berteh** [comment]
Hello @mikeevans82.

Glad the script is useful to you.

I think the convention in csv is to escape quotes by doubling it. ever tried "" ?

If that does not work you could always use single quotes as text delimiters, instead of double ones. the internal python csv parser this script uses should work just fine with no other modification.

If all that does not work I could code something to either allow to use another (custom) text delimiter character, or maybe support html entities (like &quot;), or activate different quoting options supported by python... but I'd have to dig a bit further and won't be able to in the next days... so if you want to hack the code and submit a pull request feel free to do so (in function getCsvData in file ScribusGeneratorBackend.py) !

**Comment by berteh** [comment]
tested and fixed. you can now have a double quote in the final document by putting 2 double quotes in the data (""). please update your script code (re-download) for this to work.
