### ISSUE TITLE
some empty variables not removed

### ISSUE THREAD

**Issue by berteh** [berteh/ScribusGenerator#56]
reported by @garydale:
Some empty fields are removed from the generated document and some aren't. I'm getting lots of empty lines in my .sla output file.

**Comment by berteh** [comment]
sorry to read that @garydale. 

Is it that an empty variables is not removed (i.e.you still see the %VAR_name% in the generated document? if then are you sure the value is indeed empty in the csv or is it a space character " " or something else?

Or is the problem more like the variable is removed (you don't see the %VAR_name%) but the surrounding box is not, or the surrounding spaces, or linefeeds, or tabulations are not removed whereas you think they should?

**Comment by garydale** [comment]
Looking at it in detail, I think blank lines are always showing up. What 
fooled me is that some elements don't take up a lot of space.

The %VAR variables are being removed. I think if they aren't, it's 
because the CVS column doesn't exist.

The xml-to-cvs converter I'm using is at 
http://www.convertcsv.com/xml-to-csv.htm. It has a bug that it will 
number columns if it detects multiple instances of an element but not if 
there is only one. Therefore I have 3 variables, %VAR_den%, %VAR_den/0% 
and %VAR_den/1% that always show up. They are on separate lines in my 
template.  Generally the first one contains data and the next two are blank.

The den elements always show up, as do multiple instances of location & 
mailing.

I also have 4 additional text boxes that may contain club officer 
information. There are 3 address lines that always seem to show up.

**Comment by berteh** [comment]
Hi @garydale 
the recent code change is now removing one empty lines that precedes an unused or unknown variable, as well as a list-like character... so you can generate mostly clean lists using the following text frame content in scribus:

%VAR_n1%
%VAR_n2%
%VAR_n3%
%VAR_n4%

or in an enumerated text: %VAR_n1%, %VAR_n2%, %VAR_n3%, %VAR_n4%.

**Comment by berteh** [comment]
kindly download, test, and let me know if that works for you... and %VARS.." with no corresponding column in csv should definitely be removed as well... so let me know if any is still showing in the resulting document, as it'd be a bug.

thanks.

**Comment by garydale** [comment]
The new version worked. It omitted the blank fields properly.

I didn't test it with a wrongly-named variable but I suggest that not 
removing it should be considered a feature, not a bug. It would 
highlight the fact that the template contains an error.

**Comment by garydale** [comment]
One problem: The first text element on each page (clubname) always 
exists but the second (website) doesn't. If the second element is blank, 
the first element picks up the paragraph style for the second.

In this case the first element is in a separate text frame from the 
subsequent elements. The subsequent elements flow into a second frame 
with different margins. I don't know if that is relevant or not.

**Comment by berteh** [comment]
moved your style problem to #59 to keep good track of solved/ongoing issues. kindly answer there.
B.
