### ISSUE TITLE
French characters - issue 

### ISSUE THREAD

**Issue by SANGOO** [berteh/ScribusGenerator#58]
Dear,

I'm using Scribus portable (1.4.5) in combination with your scribus generator scripts on Windows 10 machine. Contrary to the desktop version 1.4.6 that I use, the scribus generator works fine with scribus portable. 
However it struggles with French characters (è, ë, etc) and things like " ... ".
the log returns:

2016-09-03 11:18:41 - root - DEBUG - __init__:57 - ScribusGenerator initialized
2016-09-03 11:18:41 - root - DEBUG - run:69 - parsing data source file **location**/frans test.csv
2016-09-03 11:18:41 - root - DEBUG - run:108 - parsing scribus source file **location**/template framework cards.sla
2016-09-03 11:18:41 - root - DEBUG - replaceVariablesWithCsvData:378 - cleaned 1 empty variable
2016-09-03 11:18:41 - root - DEBUG - run:133 - generating reference content from row #1

If I remove all trema, accent, 3 dots ,... it works fine.

thanks for your help
Stef

**Comment by berteh** [comment]
Hi Stef.

ScribusGenerator really handles all special characters well, as long as you
provide a CSV file that is encoded in UTF-8. (I made sure of it because I'm
a French speaker too). It's tested with all kind of characters, including
Cyrillic, Japanese, webdings, accents and more.

OpenOffice is very good at creating files in utf8, excel but so much... So
I guess your CSV file has been created by excel.

A few options if that is indeed the case:

install notepad++, open your CSV with that software and change the encoding
of the file.

Find a way to make excel encode in utf8, I know there is but it changes
from one version to another so you gotta Google it.

Use a freeware to convert your CSV to utf8.

Or use open office to convert your xls to CSV.

Hope this helps.
B.

**Comment by SANGOO** [comment]
Hello Berteh,
Works as a charm.... thanks for your swift reply.
Openoffice did the trick.
Wish I had raised the question earlier ;-)

Kind regards,
Stef

**Comment by berteh** [comment]
cool.
I added some tip in https://github.com/berteh/ScribusGenerator/blob/master/README.md#the-csv-data-file for the next John doe.
If you want to share some of your creations or explain your worfklow integrating with other software don't hesitate to upload/show them in the wiki!
B.
