### ISSUE TITLE
scribus 1.5.3 - can't get %VAR_pic% to be set as "get image" input variable

### ISSUE THREAD

**Issue by gree303** [berteh/ScribusGenerator#88]
With scribus 1.5.3 it's not possible to set the %VAR_pic% variable. The 'OK' Button won't be clickable because no image is selected.
Is there any workaround or fix to that?

thanks

**Comment by berteh** [comment]
thanks for the bug report. I confirm this and will look into it. 
It seems to be  due to the recent distinction between images and vector files in ScribusSVN.

No workaround or fix yet I'm afraid.
B.

**Comment by something-strange-to-eat** [comment]
In Scribus 1.5.4 a workaround is to simply select an image in the target folder (which enables the 'OK' Button) and then type %VAR_pic%.

Isn't this working for 1.5.3 as well?

**Comment by berteh** [comment]
Yep. Selecting any image and then changing manually the name of the file to be included works. As it is an acceptable solution to me I'll close this issue. If you consider this is not usable enough kindly suggest a better way.

**Comment by gordsellar** [comment]
On Mac, once you edit the contents of the filename after clicking on it, the 'OK' button becomes disabled again. (I'm guessing something in the program, or the way it interfaces with finder) prevents you entering a filename for a nonexistent file. 

There is a workaround, though: you can create files (with no extension) in the directory where the logo files/image files are. You need to create one for each header in the CSV for an image, and name it "%VAR_[columnname]%. At least, I got it to work for me. It's bit of a pain, though, since you need to create one fake file to match each header in the csv related to a graphic included. But it's better than nothing, I guess, till a better solution is possible. 

I figured I'd post it so Bertrand knows, but also in case any other Mac users run into this issue.

**Comment by cummingsrob** [comment]
On Windows 10, the Open button becomes disabled again. I found that I can name an image file in my project folder %VAR_pic%.jpg and select that. In my data file, I had to omit the .jpg extension in the data in the 'pic' column, though. The actual %VAR_pic%.jpg place holder file in the Scribus layout gets replaced with the appropriate file from the data row.
