### ISSUE TITLE
The Script works well with all the fields in the csv table except with the images

### ISSUE THREAD

**Issue by jaimier** [berteh/ScribusGenerator#95]
Hi, thank you very much in advance for your kindness in helping me.
I work with Scribus 1.4.6 for Linux (Linux Mint 17.3 Rosa) and the latest version of Scribus Generator.
For example:
a. I open the file .../ScribusGenerator-master/example/Business_Card_testEmpty.sla
b. I run the Scribusgenerator.py script
c. Them:
Scribus File: .../ScribusGenerator-master/example/Business_Card_testEmpty.sla
Data File: .../ScribusGenerator-master/example/Business_Card.csv
Data File Separator ,
I choose the exit directory in: .../pdf
Output File Name: blank
Output Format: pdf
Keep Scribus Files: Yes
d. Generate
e. Done. Generated Files are ...
f. Ok
The result is that:
In the pdf directory are all the generated .pdf files without images and all the .sla
The .sla files instead of the image have the text of the image "foot.pdf..."
Everything else works perfect
Thanks again for your help and forgive me for my bad English
Greetings,
James

**Comment by jaimier** [comment]
With Windows XP executed from VirtualBox the result is the same, the images are not inserted, only the name

**Comment by jvr14115** [comment]
I have experienced sensitivity towards folder locations for templates, csv, content and output. Also adding a "fixed" image from a different folder can lead to issues.
If you want to test:
1. create a folder and put in your images and csv
2. create a template also saved in this folder.
3. add 1 image from this folder before using "get image" and typing the VAR's
4. run script with output set to the same folder.
If this is working: the issue has to do with paths. I think putting the full path to the images in the csv rather than just the name can resolve the issue.

**Comment by jvr14115** [comment]
Just a further comment to above post:
Scribus normally "pics" a start path for images based on the 1st image placed.
If you have images in subfolders, make sure to place 1 image from the parent folder before making further image frames.
In your csv, name your images like "subfolder\Image.jpg"
Hope this helps

**Comment by berteh** [comment]
Hello @jaimier 
To follow up on the very accurate explanations of  @jvr14115 : the path to the images must be the same in your template and in your generated documents. In your example you could simple set your output directory to .../ScribusGenerator-master/example/ to make things work.
