### ISSUE TITLE
Alternate to PDF (Scribus PDF issue)

### ISSUE THREAD

**Issue by sg000** [berteh/ScribusGenerator#99]
Per this: https://bugs.scribus.net/view.php?id=13094
There is an issue with quality output of PDF from Scribus 1.4.6 (current Dec 2017)
And it doesn't look like its getting fixed anytime soon. (tested pre-release 1.5)
Is there an easy way to change the PDF output to a PNG or something else that will provide full quality?

To be honest I haven't searched for something that would open all the sla and then create images.

**Comment by jvr14115** [comment]
If it is possible to change the export to png, Berteh will need to answer.
Personally I have no issues with the pdf quality. Did you set the export settings in the template in the right way? As far as I know, SG uses the template pdf settings.

**Comment by berteh** [comment]
Hello @sg000, 

Sorry I did not read your issue report earlier, don't know why I got no notification this time.

That being said, the bug you point to does not refer to a quality problem of PDF output. The PDF output of Scribus works fine in 1.4 and 1.5 branches, AFAIK.  This bug describes a quality loss if you generate an image output (for instance png or jpg) of a Scribus file that does include a pdf document in an image frame... since the content of image frames are rasterized (at a low resolution; hence the problem) to be included in the generated image.

@jvr14115 is right to say ScribusGenerator relies completely on Scribus to render the file, including all settings (size, resolution, color profile, marks...) you may have saved in the template document. So; if anything goes fine with Scribus, it should go fine with SG, and if something goes wrong in Scribus, SG will not provide a fix.

I hope this answer made things clear for you. As far as generating PDF document goes you should be fine, so I close this issue. If you nevertheless have problems with SG feel free to open a new issue here, I usually answer faster! ... and if you have problems with the "normal" Scribus export, then kindly rather ask the people from Scribus at https://www.scribus.net/how-to-get-support-or-contact-the-team/

Berteh.

**Comment by sg000** [comment]
Thank you for the explanation.
